// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi8NvIWbeY6kTwbhKpAtnVAs0A55G8krg',
    appId: '1:294748943571:web:130baa87e631c69623d026',
    messagingSenderId: '294748943571',
    projectId: 'gov-auction',
    authDomain: 'gov-auction.firebaseapp.com',
    storageBucket: 'gov-auction.appspot.com',
    measurementId: 'G-X691T8L2BL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMM6zzMcePwQ8FPTKwHImWE8KAs8YqN5g',
    appId: '1:294748943571:android:b6f6fc66877aff6123d026',
    messagingSenderId: '294748943571',
    projectId: 'gov-auction',
    storageBucket: 'gov-auction.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCgqXDyuGvQtJNFxbKQ9EI8Kqe33tRtg',
    appId: '1:294748943571:ios:159a9eeca4e65f4123d026',
    messagingSenderId: '294748943571',
    projectId: 'gov-auction',
    storageBucket: 'gov-auction.appspot.com',
    iosClientId: '294748943571-ocq5a4k937v0ouu99ias0qo1j0bi50tt.apps.googleusercontent.com',
    iosBundleId: 'studio.lemorange.govauction',
  );
}
